services:
  ffc-ahwr-document-generator:
    build:
      context: .
      target: production
    image: ffc-ahwr-document-generator
    container_name: ffc-ahwr-document-generator
    depends_on:
      - ffc-ahwr-document-generator-postgres
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-ahwr-document-generator-local
      APPLICATIONINSIGHTS_CONNECTION_STRING: ${APPLICATIONINSIGHTS_CONNECTION_STRING}
      APPLICATIONDOCCREATIONREQUEST_QUEUE_ADDRESS: ${APPLICATIONDOCCREATIONREQUEST_QUEUE_ADDRESS:-ffc-ahwr-document-request}${MESSAGE_QUEUE_SUFFIX}
      AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING:-changeme}
      AZURE_STORAGE_ACCOUNT_NAME: ${AZURE_STORAGE_ACCOUNT_NAME:-devstoreaccount1}
      AZURE_STORAGE_USE_CONNECTION_STRING: "true"
      CARBON_COPY_EMAIL_ADDRESS: ${CARBON_COPY_EMAIL_ADDRESS:-test@test.com}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER}
      NOTIFY_API_KEY: ${NOTIFY_API_KEY:-changeme}
      NOTIFY_TEMPLATE_ID_FARMER_APPLICATION_COMPLETE: ${NOTIFY_TEMPLATE_ID_FARMER_APPLICATION_COMPLETE:-b507dfc3-1f73-4ad9-b0ea-77df954303b9}
      NOTIFY_TEMPLATE_ID_FARMER_APPLICATION_COMPLETE_NEW_USER: ${NOTIFY_TEMPLATE_ID_FARMER_APPLICATION_COMPLETE_NEW_USER:-7d720ff7-4d1b-438c-b79d-6a34a985538f}
      NOTIFY_TEMPLATE_ID_FARMER_APPLICATION_COMPLETE_EXISTING_USER: ${NOTIFY_TEMPLATE_ID_FARMER_APPLICATION_COMPLETE_EXISTING_USER:-58ac9fbe-1cdc-4305-be1c-a4e4ac3232a7}
      NOTIFY_TEMPLATE_ID_FARMER_APPLICATION_COMPLETE_EXISTING_USER_REJECTED_WITHIN_10_MONTHS: ${NOTIFY_TEMPLATE_ID_FARMER_APPLICATION_COMPLETE_EXISTING_USER_REJECTED_WITHIN_10_MONTHS:-97b97236-2b7b-47f8-9ea9-9ad78e653d08}
      POSTGRES_DB: ffc_ahwr_document_generator
      POSTGRES_HOST: ${POSTGRES_HOST:-ffc-ahwr-document-generator-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_SCHEMA_PASSWORD:-ppp}
      POSTGRES_PORT: 5432
      POSTGRES_SCHEMA_NAME: ${POSTGRES_SCHEMA_NAME:-public}
      POSTGRES_USERNAME: ${POSTGRES_SCHEMA_USERNAME:-postgres}
      TERMS_AND_CONDITIONS_URL: ${TERMS_AND_CONDITIONS_URL:-http://localhost:3000/apply/terms}
      APPLY_SERVICE_URI: http://localhost:3000/apply
      CLAIM_SERVICE_URI: http://localhost:3004/claim
      ENDEMICS_ENABLED: ${ENDEMICS_ENABLED:-false}

  ffc-ahwr-document-generator-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: ffc_ahwr_document_generator
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ffc-ahwr-document-generator-azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.17.1
    command: "azurite-blob --loose --blobHost 0.0.0.0"

volumes:
  postgres_data: {}
