# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-ahwr-document-generator:
    build:
      target: development
    image: ffc-ahwr-document-generator-development
    container_name: ffc-ahwr-document-generator-development
    environment:
      USE_PRETTY_PRINT: ${USE_PRETTY_PRINT:-true}
    ports:
      - "3006:3000"
      - "9236:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json

  ffc-ahwr-document-generator-postgres:
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ffc-ahwr-document-generator-azurite:
    volumes:
      - azurite_data:/data
    ports:
      - "10008:10000"

volumes:
  azurite_data:
  postgres_data:
