apiVersion: v2
description: Generate and send documents for AHWR
name: ffc-ahwr-document-generator
# this version is automatically updated in the build pipeline
version: 1.0.0
dependencies:
- name: ffc-helm-library
  version: 5.0.6
  repository: https://raw.githubusercontent.com/defra/ffc-helm-repository/master/
