{{- include "ffc-helm-library.container-config-map" (list . "ffc-ahwr-document-generator.config-map") -}}
{{- define "ffc-ahwr-document-generator.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  PORT: {{ quote .Values.container.port }}
  APPINSIGHTS_CLOUDROLE: {{ quote .Values.name }}
  APPLICATIONDOCCREATIONREQUEST_QUEUE_ADDRESS: {{ quote .Values.container.applicationDocCreationRequestQueueAddress }}
  AZURE_STORAGE_USE_CONNECTION_STRING: {{ quote .Values.container.azureStorageUseConnectionString }}
  AZURE_STORAGE_ACCOUNT_NAME: {{ quote .Values.container.azureStorageAccountName }}
  CARBON_COPY_EMAIL_ADDRESS: {{ quote .Values.container.carbonCopyEmailAddress }}
  MESSAGE_QUEUE_HOST: {{ quote .Values.container.messageQueueHost }}
  NOTIFY_TEMPLATE_ID_FARMER_APPLICATION_COMPLETE: {{ quote .Values.container.notifyTemplateIdFarmerApplicationComplete }}
  POSTGRES_DB: {{ quote .Values.postgresService.postgresDb }}
  POSTGRES_HOST: {{ quote .Values.postgresService.postgresExternalName }}
  POSTGRES_PORT: {{ quote .Values.postgresService.postgresPort }}
  POSTGRES_SCHEMA_NAME: {{ quote .Values.postgresService.postgresSchema }}
  TERMS_AND_CONDITIONS_URL: {{ quote .Values.container.termsAndConditionsUrl }}
  APPLY_SERVICE_URI: {{ quote .Values.container.applyServiceUri }}
  CLAIM_SERVICE_URI: {{ quote .Values.container.claimServiceUri }}
{{- end -}}
