{{- include "ffc-helm-library.container-secret" (list . "ffc-ahwr-document-generator.container-secret") -}}
{{- define "ffc-ahwr-document-generator.container-secret" -}}
stringData:
  {{- if .Values.appInsights.key }}
  APPLICATIONINSIGHTS_CONNECTION_STRING: {{ quote .Values.appInsights.connectionString }}
  {{- end }}
{{- end -}}
